from abc import ABC, abstractmethod
from typing import List, Optional
from ..entities.transactions import Transactions
from ..enums.transaction_type_enum import TransactionTypeEnum

class ITransactionsRepository(ABC):
    
    @abstractmethod
    def get_transaction(self, transaction_id: str) -> Optional[Transactions]:
        """
        Returns the Transaction with the given ID.
        If the Transaction does not exist, returns None.
        """
        pass

    @abstractmethod
    def get_all_transactions(self) -> List[Transactions]:
        """
        Returns a list of all Transactions.
        May return an empty list if there are no transactions.
        """
        pass
    
    @abstractmethod
    def create_transaction(self, transaction: Transactions) -> Transactions:
        """
        Creates a new Transaction in the repository.
        Returns the created Transaction (may include an ID generated by the repository).
        """
        pass

    @abstractmethod
    def delete_transaction(self, transaction_id: str) -> Optional[Transactions]:
        """
        Deletes a Transaction from the repository based on ID.
        Returns the deleted Transaction or None if not found.
        """
        pass

    @abstractmethod
    def update_transaction(self, 
                           transaction_id: str, 
                           transaction_type: Optional[TransactionTypeEnum] = None, 
                           value: Optional[float] = None, 
                           current_balance: Optional[float] = None, 
                           timestamp: Optional[float] = None) -> Optional[Transactions]:
        """
        Updates an existing Transaction.
        Returns the updated Transaction or None if not found.
        Note: Financial transactions are generally immutable.
        This method is provided for symmetry with other repositories,
        but its use should be considered carefully.
        """
        pass
